version: 0.2

phases:
  install:
    commands:
      - echo Installing Node ...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm install
  build:
    commands:
      - echo Bulding ...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
